version: "3"
services:
  web:
    build: .
    container_name: weblog_dev
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    command: ["tail", "-f", "/dev/null"]
    working_dir: /myapp
networks:
  default:
    external:
      name: services
