version: "3"
services:
  web:
    build: .
    container_name: dotnet_weblog
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    command: ["tail", "-f", "/dev/null"]
    working_dir: /myapp
networks:
  default:
    external:
      name: services
